import json

from google_form_package import Sheet


def main():
    web_sheet = Sheet()
    occ_sheet = web_sheet.get_worksheet("Occupation")
    va_sheet = web_sheet.get_worksheet("Vacancies")
    progress_sheet = web_sheet.get_worksheet("Progress")
    occ_sheet.update([["Scrapping Finished"]], "R1")
    va_sheet.update([["Scrapping Finished"]], "Q1")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "UrlNum": 1})]], range_name="A1")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 0})]], range_name="A2")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 1})]], range_name="B2")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 2})]], range_name="C2")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 3})]], range_name="D2")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 4})]], range_name="E2")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "UrlNum": 1})]], range_name="A3")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 0})]], range_name="A4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 1})]], range_name="B4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 2})]], range_name="C4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 3})]], range_name="D4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 4})]], range_name="E4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 5})]], range_name="F4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 6})]], range_name="G4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 7})]], range_name="H4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 8})]], range_name="I4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 9})]], range_name="J4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 10})]], range_name="K4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 11})]], range_name="L4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 12})]], range_name="M4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 13})]], range_name="N4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 14})]], range_name="O4")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 0})]], range_name="A5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 1})]], range_name="B5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 2})]], range_name="C5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 3})]], range_name="D5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 4})]], range_name="E5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 5})]], range_name="F5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 6})]], range_name="G5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 7})]], range_name="H5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 8})]], range_name="I5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 9})]], range_name="J5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 10})]], range_name="K5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 11})]], range_name="L5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 12})]], range_name="M5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 13})]], range_name="N5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 14})]], range_name="O5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 15})]], range_name="P5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 16})]], range_name="Q5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 17})]], range_name="R5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 18})]], range_name="S5")
    progress_sheet.update(values=[[json.dumps({"progress": "setting", "RowNum": 19})]], range_name="T5")
if __name__ == "__main__":
    main()
