name: Run Scrapping

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-occupation-scraping:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Google Chrome
      run: |
        set -ex
        sudo apt-get update -y
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        sudo apt-get install -y -f
    
    - name: Install Chromedriver
      run: |
        sudo apt-get install -y unzip jq
        URL=$(curl -sS https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r '.channels.Stable.downloads.chromedriver.url')
        wget "$URL" -O chromedriver.zip
        unzip chromedriver.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Occupation Scraping
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      run: |
        python main.py

    - name: Upload occupation progress artifact
      uses: actions/upload-artifact@v4
      with:
        name: occupation-progress
        path: occupation_progress.txt
        
  run-vacancies-scraping:
    runs-on: [self-hosted, runner]
    timeout-minutes: 0

    steps:
    - name: Wait for 15 minutes
      shell: powershell
      run: Start-Sleep -Seconds 900

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      shell: powershell
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Vacancies Scraping
      shell: powershell
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      run: |
        python vacancy.py
        
    - name: Upload vacancy progress artifact
      uses: actions/upload-artifact@v4
      with:
        name: vacancy-progress
        path: progress.txt
